#!/bin/bash

target=$SMB_CONF_DIR/migration
mkdir -p $target

ufile=$target/users.mg
gfile=$target/groups.mg

usradmin -e -u $ufile -g $gfile
echo "Users and Groups have been backed up in $ufile and $gfile"
echo "WARN: You have to backup your passwdb file manually."

