#!/bin/bash

target=$SMB_CONF_DIR/migration
ufile=$target/users.mg
gfile=$target/groups.mg

[ -f $ufile ] || { echo "Can't find users backup file"; exit 1; }
[ -f $gfile ] || { echo "Can't find groups backup file"; exit 1; }

usradmin -i -u $ufile -g $gfile

echo "Users and Groups have been successfully imported"
echo "WARN: You have to restore your passwdb file manually."
