#!/bin/bash

Upasswd=/etc/passwd
Ushadow=/etc/shadow
Group=/etc/group
Gshadow=/etc/gshadow

if [[ $EUID -ne 0 ]]; then
    echo "Permission denied, should be run as root"
    exit 1
fi

progname=$0

function usage () {
   cat <<EOF
Usage: $progname [options] -{e|i}
  -h    show this help message and exit
  -i    import from backupfile
  -e    export from backupfile
  -u    backup file for users
  -g    backup file for groups
EOF
   exit 0
}

[ "$#" = "0" ] && usage

while getopts "ieu:g:h" opt; do
    case $opt in
        i )  acti="import" ;;
        e )  acte="export" ;;
        u )  ufile=$OPTARG ;;
        g )  gfile=$OPTARG ;;
        h )  echo "found $opt" ; usage ;;
        \?)  usage ;;
    esac
done

if [ -n "$acti" ] && [ -n "$acte" ]; then
    echo "ERROR: -e and -i options are given concurrently"
    exit 1
fi

if [ -z "$ufile" ] && [ -z "$gfile" ]; then
    echo "ERROR: -u or -g option must occur"
    exit 1
fi

function expt() {
    # Export users
    if [ -n "$ufile" ]; then
        join -t ':' -1 1 <(awk -F ':' '($3 >= 1000 && $3 != 65534){print $0}' $Upasswd | sort -t ':' -k 1,1) -2 1 <(sort -t ':' -k 1,1 $Ushadow) > $ufile
        chmod 0600 $ufile
    fi

    # Export groups
    if [ -n "$gfile" ]; then
        join -t ':' -1 1 <(awk -F ':' '($3 >= 1000 && $3 != 65534){print $0}' $Group | sort -t ':' -k 1,1) -2 1 <(sort -t ':' -k 1,1 $Gshadow) > $gfile
        chmod 0600 $gfile
    fi

    exit 0
}

function impt() {
    # Import users
    join -v 1 -t ':' -1 1 <(awk -F ':' '($3 >= 1000 && $3 != 65545){print $0}' $ufile | sort) \
                     -2 1 <(sort -t ':' -k 1,1 $Upasswd) \
    | tee >(cut -d ':' -f 1-7 >> $Upasswd) | cut -d ':' -f 1,8- >> $Ushadow

    # Import groups
    join -v 1 -t ':' -1 1 <(awk -F ':' '($3 >= 1000 && $3 != 65534){print $0}' $gfile | sort) \
                     -2 1 <(sort -t ':' -k 1,1 $Group) \
    | tee >(cut -d ':' -f 1-4 >> $Group) \
    | cut -d ':' -f 1,5- >> $Gshadow

    exit 0
}

[ -n "$acte" ] && expt
[ -n "$acti" ] && impt

